export default {
  catalog: [
    {
      name: "Лента светодиодная ELF 300SMD2835-GERMES-W",
      src: "/img/17.png",
      price: "2319",
      category: "Диодная лента",
      quantity: 1,
    },
    {
      name: "Лента светодиодная ЭРА LS5050-60LED-IP20-RGB-eco-3m Б0035605",
      src: "/img/18.png",
      price: "639",
      category: "Диодная лента",
      quantity: 1,
    },
    {
      name: "Лента светодиодная GENERAL LIGHTING SYSTEMS GLS-5050-60-14.4-12-IP20-6",
      src: "/img/19.png",
      price: "451",
      category: "Диодная лента",
      quantity: 1,
    },
    {
      name: "Розетка 2P+E, 16А, белый ATLAS DESIGN",
      src: "/img/16.png",
      price: "137.75",
      category: "Розетки и выключатели",
      quantity: 1,
    },
    {
      name: "Таймер розеточный, 7-дневная программа 16 А TDM",
      src: "/img/12.png",
      price: "779.00",
      category: "Розетки и выключатели",
      quantity: 1,
    },
    {
      name: "Прожектор светодиодный ОНЛАЙТ 71658 OFL-30-6K-BL-IP65-LED",
      src: "/img/20.png",
      price: "529",
      category: "Светильники и прожекторы",
      quantity: 1,
    },
    {
      name: "Прожектор светодиодный NAVIGATOR NFL-01-30-6.5K-LED",
      src: "/img/21.png",
      price: "565",
      category: "Светильники и прожекторы",
      quantity: 1,
    },
    {
      name: "Реле контроля напряжения АЗМ LED-63А-220В TDM",
      src: "/img/15.png",
      price: "1681.50",
      category: "Автоматы, УЗО, рубильники",
      quantity: 1,
    },
    {
      name: "Реле контроля напряжения RBUZ D63t",
      src: "/img/13.png",
      price: "3705.00",
      category: "Автоматы, УЗО, рубильники",
      quantity: 1,
    },
    {
      name: `Лампа LED "груша" Е27 11Вт (990Лм) 4000К 230В IEK ECO`,
      src: "/img/14.png",
      price: "84.55",
      category: "Лампочки",
      quantity: 1,
    },
    {
      name: "Нагревательный мат для теплого пола SUN POWER SPCM-2,0",
      src: "/img/22.png",
      price: "4415",
      category: "Тёплый пол",
      quantity: 1,
    },
    {
      name: "Центр управления умным домом AQARA Hub M1S EU HM1S-G01",
      src: "/img/23.png",
      price: "4109",
      category: "Умный дом",
      quantity: 1,
    },
    {
      name: "Блок управления PHILIPS Hue Bridge 929001180629",
      src: "/img/24.png",
      price: "4990",
      category: "Умный дом",
      quantity: 1,
    },
    {
      name: "Кабель силовой алюминиевый бронированный 4х16 мм",
      src: "/img/11.png",
      price: "222.30",
      category: "Провода, кабели",
      quantity: 1,
    },
  ],
};
